# Generated by Django 2.2.24 on 2021-10-26 05:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('ty1', 'TP1'), ('ty2', 'TP2')], max_length=2)),
                ('framework', models.CharField(choices=[('fw1', 'FW1'), ('fw2', 'FW2')], max_length=2)),
                ('domain_name', models.CharField(max_length=50, null=True)),
                ('screenshot', models.CharField(max_length=100, null=True, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
