# Generated by Django 2.2.24 on 2021-10-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20211026_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='framework',
            field=models.CharField(choices=[('fw1', 'Django'), ('fw2', 'React Native')], max_length=50),
        ),
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.CharField(choices=[('ty1', 'Web'), ('ty2', 'Mobile')], max_length=50),
        ),
    ]
