# Generated by Django 2.2.24 on 2021-11-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20211028_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='framework',
            field=models.CharField(choices=[('fw1', 'Django'), ('fw2', 'React Native')], default='Django', max_length=50),
        ),
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.CharField(choices=[('ty1', 'Web'), ('ty2', 'Mobile')], default='Web', max_length=50),
        ),
    ]
